"""Generate VOCABULARY.md — every classification axis and its members.

The axes are defined in two places by design: the allowed values and what they
mean live in `schema.py`, next to the validation that enforces them, while
membership lives in the legend ECSV files, because which telescope is a Cherenkov
telescope is data. Neither is the wrong home, but the split means no single file
answers "what classes exist and what is in them".

This tool answers it, by reading both. Re-run it after changing either:

    python tools/vocabulary_reference.py

Do not hand-edit the output. A third copy of this information would drift from
the other two, which is how the database acquired its worst defect: a template
nobody updated seeded 351 files with a malformed key.
"""

from __future__ import annotations

from pathlib import Path

from gdmbounds import schema

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "VOCABULARY.md"


def table(rows: list[tuple[str, ...]], headers: tuple[str, ...]) -> str:
    line = "| " + " | ".join(headers) + " |"
    rule = "|" + "|".join("---" for _ in headers) + "|"
    body = "\n".join("| " + " | ".join(cells) + " |" for cells in rows)
    return f"{line}\n{rule}\n{body}\n"


def per_bound_axis(name: str, key: str, values: dict[str, str], note: str) -> str:
    rows = [(f"`{value}`", description) for value, description in values.items()]
    return (
        f"## {name}\n\n"
        f"Recorded in every bound's header as `{key}`.\n\n"
        f"{table(rows, ('value', 'meaning'))}\n{note}\n"
    )


def per_entity_axis(
    name: str, legend: str, column: str, classes: dict[str, str],
    membership: dict[str, str], labels: dict[str, str],
) -> str:
    rows = []
    for value, description in classes.items():
        members = sorted(k for k, v in membership.items() if v == value)
        shown = ", ".join(f"`{m}`" for m in members) or "*(none)*"
        rows.append((f"`{value}`", description, f"{len(members)}", shown))
    unclassified = sorted(k for k, v in membership.items() if v not in classes)
    body = (
        f"## {name}\n\n"
        f"Assigned in `gdmbounds/legends/{legend}` in the `{column}` column, and "
        f"validated against the set below.\n\n"
        f"{table(rows, ('class', 'meaning', 'n', 'members'))}\n"
    )
    if unclassified:
        body += f"\n**Unclassified:** {', '.join(f'`{u}`' for u in unclassified)}\n"
    return body


def main() -> int:
    v = schema.load_vocabulary()

    parts = [
        "# Vocabulary\n",
        "*Generated by `tools/vocabulary_reference.py`. Do not edit by hand — "
        "re-run the tool; `pytest` fails if this file is out of date.*\n",
        "Every axis a bound can be selected along. Two kinds: values carried by each "
        "bound in its own header, and classes assigned to instruments, targets and "
        "channels in the legend files.\n",
        "In code, `gdmbounds.load_vocabulary()` returns the same information, and "
        "`.describe()` prints it.\n",
        "---\n",
        "# Carried by each bound\n",
        per_bound_axis(
            "Process", "mode", schema.MODES,
            "Fixed by the physics of the result and never inferred.",
        ),
        per_bound_axis(
            "Provenance", "origin", schema.ORIGINS,
            "Separates a collaboration's own result from an analysis of public data "
            "published by individual authors.",
        ),
        per_bound_axis(
            "Kind of statement", "statement", schema.STATEMENTS,
            "Plotting a projected sensitivity beside a measured limit without "
            "distinguishing them is the most misleading thing this database could do.",
        ),
        per_bound_axis(
            "Assumed halo profile", "profile", schema.PROFILES,
            "**Optional.** Recorded where the source states it. A missing `profile` "
            "means nobody wrote it down, *not* that no profile was assumed — every "
            "J-factor rests on one. Any selection filtering on it silently drops the "
            "bounds that do not declare one, and should say so.",
        ),
        "---\n",
        "# Assigned in the legends\n",
        per_entity_axis(
            "Instrument classes", "legend_instruments.ecsv", "class",
            schema.INSTRUMENT_CLASSES, v.instrument_class, v.instruments,
        ),
        per_entity_axis(
            "Target classes", "legend_targets.ecsv", "class",
            schema.TARGET_CLASSES, v.target_class, v.targets,
        ),
        per_entity_axis(
            "Channel spectra", "legend_channels.ecsv", "spectrum",
            schema.CHANNEL_SPECTRA, v.channel_spectrum, v.channels,
        ),
        "---\n",
        "# Adding a value\n",
        "A new class goes in `schema.py`, beside the set it joins, with a sentence "
        "saying what it means. A new instrument, target or channel goes in the "
        "matching legend file **with its class filled in** — `pytest` fails on a "
        "blank or misspelled one. Then re-run this tool.\n",
    ]
    OUT.write_text("\n".join(parts))
    print(f"{OUT.name}: {len(schema.INSTRUMENT_CLASSES)} instrument classes, "
          f"{len(schema.TARGET_CLASSES)} target classes, "
          f"{len(schema.CHANNEL_SPECTRA)} channel spectra")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
